version: "3.6"
services:
    ctcache:
        build: .
        environment:
            CTCACHE_PORT: 5000
        ports:
            - "5000:5000"
        volumes:
            - "ctcache:/var/lib/ctcache"
volumes:
    ctcache:
